# Request codes
REGISTER_REQUEST = 1000
GET_CLIENTS_LIST_REQUEST = 1001
GET_CLIENT_PUBLIC_KEY_REQUEST = 1002
SEND_CLIENT_MESSAGE_REQUEST = 1003
GET_WAITING_MESSAGES_REQUEST = 1004

# Successful response codes
REGISTRATION_SUCCESSFUL_RESPONSE = 2000
CLIENTS_LIST_RETURNED_RESPONSE = 2001
CLIENT_PUBLIC_KEY_RETURNED_RESPONSE = 2002
MESSAGE_SENT_TO_CLIENT_RESPONSE = 2003
WAITING_MESSAGES_RETURNED_RESPONSE = 2004

# Error response codes
GENERAL_ERROR = 9000
